Scrum 109 criar endpoint de alterar senha
Somehow-I-Code/marquei pull request #102
Opened 2024-06-12 20:48 UTC by JaqAmaral

# Criando endpoint e rota para alterar senha

## Qual problema esse pull request resolve?
Este PR implementa uma nova rota de PUT para atualização de senha, criando um endpoint "/change-password". O objetivo é implementar a lógica necessária para permitir que os usuários alterem suas senhas. Além disso, a rota faz uso de um token JWT para autenticar e identificar o usuário.

## Como o seu código resolve esse problema?

- Foi criada uma rota utilizando o método PUT para atualização de senha.
- Um endpoint “/change-password” foi configurado para receber as requisições de alterar a senha.
- Autenticação por token que verifica e decodifica o token JWT para obter o ID do usuário autenticado.
- Utilizando o ID do perfil extraído do token, o sistema busca e exibe as informações do usuário cadastrado.
- Tem criar uma requisição PUT (local-requests), para exibir as informações do perfil do usuário, mas não realiza a atualização da senha. Esta funcionalidade será implementada em um pull request futuro.

## Quais os passos para testar essa feature/bug?

- No terminal, execute o comando **`make run`**
- Criar uma requisição PUT, que envia o HTTP PUT para o endpoint **`“/change-password”`** com um token JWT válido.
- Observe que, neste momento, a funcionalidade apenas exibe as informações do perfil do usuário sem realizar a atualização da senha

2024-06-13 01:11 UTC, GiAmaral commented on api/src/http/routes/put-password.ts
> +
Excluir essa linha extra

2024-06-13 01:11 UTC, GiAmaral commented on api/src/http/routes/put-password.ts
> +                .code(500)
O certo é reply.status(500)

2024-06-13 12:07 UTC, JaqAmaral commented on api/src/http/routes/put-password.ts
> +                .code(500)
Vou corrigir

2024-06-13 17:18 UTC, RafaRafa26 approved these changes

2024-06-14 10:45 UTC, GiAmaral approved these changes

2024-06-14 10:46 UTC, goislimat requested changes

2024-06-14 10:46 UTC, goislimat commented on api/index.ts
> +server.register(putPassword);
`putPassword` não é um bom nome. O melhor aqui seria `changePassword`. Os verbos `get` funcionam bem no nome bem como o `delete`, mas `post` vira `create` e `put` fica melhor como `change`.

2024-06-14 10:46 UTC, goislimat commented on api/src/http/routes/put-password.ts
> +    server.put("/change-password", async (request, reply) => {
O melhor verbo http aqui é o `patch`. O `patch` é usado quando um endpoint é chamada com a intenção de alterar uma pequena parte dos dados (como a senha apenas aqui nesse PR).

O verbo `put` a gente costuma usar quando há a possibilidade de alterar todos os dados em um determinado endpoint. Por exemplo: quando formos adicionar uma tela pra alterar os dados do recurso, vamos manda tudo relacionado ao recurso e não apenas um dado específico. Nesse caso, o melhor verbo seria o `put`.

2024-06-17 12:07 UTC, goislimat approved these changes

2024-06-17 19:05 UTC, merged