Add arquivos http todas rotas
Somehow-I-Code/marquei pull request #122
Opened 2024-08-20 17:35 UTC by JaqAmaral

# HTTP EM TODAS AS ROTAS

## Qual problema esse pull request resolve?
Este pull request resolve a falta de um arquivo de http para completar de todas as rotas do projeto. Com isso, todos arquivos para realizar teste no REST CLIENTE.

## Como o seu código resolve esse problema?
Na pasta `api/requests` foi criado um novo arquivo chamado `change-password.http`, pois era o único que estava faltando para completar todas as rotas.

## Quais os passos para testar essa feature/bug?
- No terminal, digite: `make run`.
- Entre na pasta `api/requests` para realizar testes em todas https existentes.

2024-08-20 18:03 UTC, GiAmaral requested changes

2024-08-20 18:03 UTC, GiAmaral commented on api/requests/profiles/change-password.http
> +@authToken = Baerer {{login.response.body.$.token}}
Se não me engano é `Bearer`, o "e" vem antes do "a"

2024-08-20 19:46 UTC, JaqAmaral commented on api/requests/profiles/change-password.http
> +@authToken = Baerer {{login.response.body.$.token}}
Corrigido

2024-08-22 10:25 UTC, goislimat approved these changes

2024-08-22 17:49 UTC, RafaRafa26 approved these changes

2024-08-23 00:41 UTC, GiAmaral approved these changes

2024-08-23 17:48 UTC, merged