Create profiles list endpoint
Somehow-I-Code/marquei pull request #126
Opened 2024-08-30 17:57 UTC by RafaRafa26

# [Título do seu pull request]

## Qual problema esse pull request resolve?

## Como o seu código resolve esse problema?

## Quais os passos para testar essa feature/bug?

Tete com perfil USER

![Captura de tela 2024-08-30 144900](https://github.com/user-attachments/assets/2a74667b-4fad-4a58-afda-6911fa73f04c)

Teste com perfil ADMIN

![Captura de tela 2024-08-30 145046](https://github.com/user-attachments/assets/e45f7be1-1a9f-47b4-8095-41e6723db75b)

Teste com perfil SUDO

![Captura de tela 2024-08-30 145210](https://github.com/user-attachments/assets/214b564c-71e1-4b90-be37-a268e0df8234)

2024-09-02 17:52 UTC, RafaRafa26 commented
@goislimat minhas dúvidas são como buscar os perfis de cada company e exibir eles na tela profiles list.

2024-09-02 20:40 UTC, goislimat commented on api/src/http/routes/profiles-list.ts
> +        }
Checa se o usuário atual é admin.

Feito isso, vc vai buscar o usuário no banco de dados usando alguma informação do token (email, por exemplo).

Quando vc tiver os dados do usuário, vc vai buscar todos os usuários que tenham a mesma companyId do usuário atual.

Retorna a lista de usuários encontrados.

###########################

Checa se o usuário é sudo.

Se for, busca todos os usuários e retorna a lista com a informação.

2024-09-05 18:11 UTC, GiAmaral requested changes

2024-09-05 18:11 UTC, GiAmaral commented on api/src/http/routes/profiles-list.ts
> +}
Depois, vc faz a verificação se o usuário logado é do tipo SUDO, se for, vc faz a busca por todos os perfis cadastrados, como falei acima, algo com `findAll` do prisma (olhar o repository para entender se vc escolheu a função adequada pra busca).

Como já verificou se é ADMIN ou SUDO, se o caso for `false` retorna, no final, fora das outras duas verificações, a mensagem de que o usuário não tem permissão pra executar a ação.

2024-09-05 18:11 UTC, GiAmaral commented on api/src/http/routes/profiles-list.ts
> +            return reply.status(200).send({ profile });
Se não for criar uma função nova no repository que traz perfis da mesma Company, será preciso criar a condição de trazer apenas perfis da mesma Company, e retornar sucesso dentro dessa condição.

2024-09-05 18:11 UTC, GiAmaral commented on api/src/http/routes/profiles-list.ts
> +            level: Level;
Acho que vc vai ter que pegar a `companyId` do token, pois precisará pro caso do usuário tipo ADMIN, é isso mesmo @goislimat ?

2024-09-05 20:42 UTC, goislimat commented on api/src/http/routes/profiles-list.ts
> +        if (userProfile.level === Level.USER) {
Aqui meio que tanto faz. Ele tbm pode checar se é user e adim e o que sobra vai ser sudo ou pode olhar se é user e sudo e o que sobrar vai ser admin. A combinação não tem tanto impacto aqui.

2024-09-05 20:44 UTC, goislimat commented on api/src/http/routes/profiles-list.ts
> +                userProfile.email,
É isso mesmo. Se for admin vc vai pegar todos os usuários e a cláusula de filtro (where) vai ser aqueles que tem a mesma companyId do usuário logado.

O findMany deve resolver seu problema aqui.

2024-09-05 20:47 UTC, goislimat commented on api/src/http/routes/profiles-list.ts
> +            if (!profile) {
Essa comparação não faz sentido aqui. Ela não faz parte da solução.

2024-09-05 20:47 UTC, goislimat commented on api/src/http/routes/profiles-list.ts
> +            return reply.status(200).send({ profile });
É isso aí. O ideal é ter uma função no repository de profiles que busque os perfis com base no companyId

2024-09-06 18:20 UTC, RafaRafa26 commented on api/src/http/routes/profiles-list.ts
> +        if (userProfile.level === Level.USER) {
@goislimat não entendi muito bem por que eu deveria checar nesse if se o usuário é ADMIN ou SUDO já que os usuários de nível USER serão os únicos que não terão acesso a esta tela?

2024-09-06 18:28 UTC, RafaRafa26 commented on api/src/http/routes/profiles-list.ts
> +                userProfile.email,
Então eu não preciso fazer esse findByEmail? Somente um findMany com where para filtrar usuários com mesmo companyId?

2024-09-12 18:36 UTC, goislimat commented on api/src/http/routes/profiles-list.ts
> +        if (
Esse código serve apenas pra admin. Admins que precisava filtrar por companyId. Os sudos têm todos os usuários retornados da busca.

2024-09-12 18:36 UTC, goislimat commented on api/src/http/routes/profiles-list.ts
> +    server.post("/profiles-list", async (request, reply) => {
Deveria ser get aqui.

2024-09-12 18:39 UTC, goislimat commented on api/src/repositories/profiles.ts
> +    async findAll(companyId: number) {
Recebe um parâmetro aqui tipo isSudo que checa se o usuário é sudo. Se não for, remove os usuários sudos restringindo a busca com a cláusula where.

2024-09-16 15:12 UTC, RafaRafa26 commented on api/src/repositories/profiles.ts
> +    async findAll(companyId: number) {
![Captura de tela 2024-04-22 121121](https://github.com/user-attachments/assets/7e436bc5-6bd1-44f9-b7f2-5ba949ed9fee)

2024-09-16 15:13 UTC, RafaRafa26 commented on api/src/repositories/profiles.ts
> +    async findAll(companyId: number) {
![Captura de tela 2024-09-16 120954](https://github.com/user-attachments/assets/7b5c5831-f6ac-4e4f-96c7-ccb139fc9ae9)

2024-09-16 16:13 UTC, goislimat commented on api/src/repositories/profiles.ts
> +    }
```suggestion
        } 
            return prisma.profile.findMany({
                where: {
                    companyId,
                    level: { not: "SUDO" },
                },
            });
    }
```

2024-09-16 16:13 UTC, goislimat commented on api/src/repositories/profiles.ts
> +    }
Não precisa do else aqui pq o return garante que nada abaixo dele vai ser executado.

2024-09-16 16:13 UTC, goislimat approved these changes

2024-09-17 19:47 UTC, JaqAmaral approved these changes

2024-09-17 21:30 UTC, goislimat commented on api/src/http/routes/profiles-list.ts
> +            return reply.status(200).send(profile);
```suggestion
            const profiles = await profileRepository.findAll(
                userProfile.companyId,
                isSudo,
            );

            return reply.status(200).send(profiles);
```

2024-09-17 21:31 UTC, goislimat commented on api/src/http/routes/profiles-list.ts
> +            userProfile.level === Level.SUDO
A @GiAmaral apontou que esse if aqui é desnecessário e é mesmo. Então vamos remover ele e só deixar o conteúdo.

2024-09-17 21:31 UTC, goislimat commented on api/src/repositories/profiles.ts
> +            });
```suggestion
            return prisma.profile.findMany();
```

Se for SUDO, deve retornar todos os perfis de todas as companyIds.

2024-09-17 21:32 UTC, goislimat commented on api/src/repositories/profiles.ts
> +            });
Outra coisa que a @GiAmaral apontou aqui.

2024-09-17 21:35 UTC, GiAmaral reviewed
O @goislimat fez as observações pra mim

2024-09-19 01:24 UTC, GiAmaral commented on api/src/http/routes/profiles-list.ts
> +        userProfile.level === Level.ADMIN || userProfile.level === Level.SUDO;
Essa comparação era do if, como o if foi retirado, essa comparação não precisa mais.

2024-09-19 01:24 UTC, GiAmaral commented on api/src/http/routes/profiles-list.ts
> +        {
Retirar chaves

2024-09-19 01:24 UTC, GiAmaral commented on api/src/http/routes/profiles-list.ts
> +        }
Retirar chaves

2024-09-19 01:24 UTC, GiAmaral commented on api/src/http/routes/profiles-list.ts
> +            const isSudo = userProfile.level == Level.SUDO;
```suggestion
            const isSudo = userProfile.level == Level.SUDO;
            const profiles = await profileRepository.findAll(
                userProfile.companyId,
                isSudo,
            );

            return reply.status(200).send(profiles);
```

2024-09-19 01:24 UTC, GiAmaral commented on api/src/http/routes/profiles-list.ts
> +            const isSudo = userProfile.level == Level.SUDO;
Sugestão de como ficaria o código

2024-09-19 20:29 UTC, GiAmaral approved these changes

2024-09-20 17:28 UTC, merged