Padronizando mensagens
Somehow-I-Code/marquei pull request #132
Opened 2024-10-10 21:49 UTC by JaqAmaral

# PADRONIZANDO AS MENSAGENS

## Qual problema esse pull request resolve?
Este pull request padroniza as mensagens de erro e sucesso, além de ajustar a pontuação, incluindo a implementação do ponto final. No entanto, as mensagens não eram padronizadas.

## Como o seu código resolve esse problema?
Alguns arquivos que continham mensagens de erro ou sucesso estavam fora de contexto, apesar de serem mensagem semelhante entre si. A solução foi padronizar todas as mensagens e implementar o ponto final, já que a maioria estava sem.

## Quais os passos para testar essa feature/bug?
- Fazer o **pull** no VS code para obter as mensagens padronizadas e com a pontuação corrigida.

2024-10-11 11:25 UTC, goislimat commented on api/src/validators/change-password.ts
> +        message: "A senha repetida deve conter no mínimo 8 caracteres, incluindo letras e números.",
O meu problema com essa mensagem é que a gente não força o usuário a digitar letras e números. A senha dele pode conter o que ele quiser desde que tenha ao menos 8 caracteres. Apesar de essa nova mensagem ser mais informativa, ela não é tão precisa quanto a anterior.

2024-10-11 11:25 UTC, goislimat commented on api/src/validators/change-password.ts
> +        message: "A senha repetida deve conter no mínimo 8 caracteres, incluindo letras e números.",
@JaqAmaral @RafaRafa26 @GiAmaral depois deixem aqui o que vcs pensam disso.

2024-10-11 11:25 UTC, goislimat commented on api/src/validators/login-form.ts
> +    password: z.string().min(8, "A senha deve conter no mínimo 8 caracteres, incluindo letras e números."),
Mesma coisa aqui.

2024-10-11 11:27 UTC, goislimat commented on web/src/app/first-login/components/first-login-reset-password.tsx
> +        message: "A senha repetida deve conter no mínimo 8 caracteres. incluindo letras ou números.",
Mesma coisa aqui

2024-10-11 11:27 UTC, goislimat commented on web/src/app/login/components/login-form.tsx
> +        message: "Digite um e-mail válido.",
Mesma coisa do email aqui

2024-10-11 11:27 UTC, goislimat commented on web/src/app/login/components/login-form.tsx
> +        message: "A senha deve conter no mínimo 8 caracteres, incluindo letras ou números.",
Mesma coisa da senha aqui

2024-10-11 11:28 UTC, goislimat commented on web/src/app/new-profile/components/new-profile-form.tsx
> +        message: "Digite um e-mail válido.",
Mesmo problema do email aqui

2024-10-11 11:28 UTC, goislimat commented on web/src/app/new-profile/components/new-profile-form.tsx
> +                return "Gerencia agendamentos, recursos, empresa e outros usuários geral.";
```suggestion
                return "Gerencia agendamentos, recursos, empresas e todos os usuários da aplicação.";
```

2024-10-11 11:29 UTC, goislimat commented on web/src/app/new-resource/components/new-resource-form.tsx
> +        message: "A descrição está muito longa.",
```suggestion
        message: "A descrição está muito longa. Máximo de 1000 caracteres.",
```

2024-10-11 14:25 UTC, RafaRafa26 commented on api/src/validators/change-password.ts
> +        message: "A senha repetida deve conter no mínimo 8 caracteres, incluindo letras e números.",
Concordo, gosto mais da mensagem anterior.

2024-10-15 20:22 UTC, JaqAmaral commented on api/src/validators/change-password.ts
> +        message: "A senha repetida deve conter no mínimo 8 caracteres, incluindo letras e números.",
Feito

2024-10-16 14:05 UTC, goislimat commented on api/src/http/routes/change-password.ts
> +                    message: "A nova senha não pode ser igual à antiga senha.",
```suggestion
                    message: "A nova senha não pode ser igual à senha antiga.",
```

2024-10-16 14:05 UTC, goislimat commented on api/src/http/routes/change-password.ts
> +                message: "A nova senha não pode ser igual à antiga senha.",
```suggestion
                message: "A nova senha não pode ser igual à senha antiga.",
```

Estou sugerindo essa mudança pq fica uma mensagem menos robótica.

2024-10-16 14:07 UTC, goislimat commented on api/src/http/routes/change-password.ts
> +                message: "A nova senha e a repetida devem ser iguais.",
```suggestion
                message: "A sua confirmação de senha não bate com a nova senha.",
```

2024-10-16 14:08 UTC, goislimat commented on api/src/http/routes/change-password.ts
> +                message: "A nova senha e a repetida devem ser iguais.",
Mesmo coisa aqui. Tentando fazer a mensagem soar mais natural.

2024-10-16 14:09 UTC, goislimat commented on api/src/validators/reset-password.ts
> +    email: z.string().email("E-mail inválido."),
```suggestion
    email: z.string().email("Email inválido."),
```

2024-10-16 14:09 UTC, goislimat commented on web/src/app/first-login/components/first-login-reset-password.tsx
> +        message: "A senha repetida deve conter no mínimo 8 caracteres.",
```suggestion
        message: "A confirmação de senha deve conter no mínimo 8 caracteres.",
```

2024-10-16 14:12 UTC, goislimat requested changes
Adicionei mais umas mudanças e respondi algumas perguntas. Quando terminar de fazer as alterações, clica no botãozinho de refresh que tem lá na lista de revisores do pull request pra que eu seja notificado de novo, por favor.

2024-10-21 19:06 UTC, GiAmaral approved these changes

2024-10-21 19:27 UTC, goislimat approved these changes

2024-10-22 21:26 UTC, merged