Implement profile search
Somehow-I-Code/marquei pull request #133
Opened 2024-10-11 16:23 UTC by RafaRafa26

# Implementar busca por perfil

## Qual problema esse pull request resolve?
Este PR implementa a busca por perfil na tela profiles list.

## Como o seu código resolve esse problema?

- O código utiliza dois estados, `search` e `filter`, para gerenciar a pesquisa. O estado `search` captura o valor digitado no campo de texto, e `filter` guarda o critério de pesquisa que será aplicado.
 
- A função `updateSearch` é responsável por capturar o valor digitado pelo usuário no campo de busca. Ela atualiza o estado `search` com o valor do campo de entrada sempre que há uma mudança, garantindo que o texto digitado seja armazenado corretamente.

- Quando o usuário clica no botão de pesquisa, a função `handleSearch` é chamada. Ela define o estado `filter` como o valor atual de `search`, disparando a filtragem da lista de perfis.

- A função de filtragem percorre a lista de perfis e verifica se algum dos campos (nome, e-mail, nível ou ocupação) contém o valor digitado pelo usuário. A busca é feita ignorando letras maiúsculas ou minúsculas, o que aumenta a flexibilidade da pesquisa.

- Se o estado `filter` estiver vazio, todos os perfis são exibidos. Caso contrário, apenas os perfis que correspondem ao filtro são mostrados na interface.

- Após a filtragem, os perfis correspondentes são renderizados na tela usando o componente `ProfileCard`, permitindo que a interface exiba apenas os perfis que atendem aos critérios de busca do usuário.

## Quais os passos para testar essa feature/bug?

2024-10-13 11:57 UTC, goislimat commented on web/src/app/profiles-list/page.tsx
> +                    }
```suggestion
if (!filter) {
    return true;
}

const formattedFilter = filter.toLowerCase();
const searchableKeys = ['name', 'email', 'level', 'occupation'];

const profileMatchFilter = searchableKeys.find((key) => {
    return profile[key].toLowerCase().includes(formattedFilter);
});

return profileMatchFilter;
```

Essa mudança deixa o código menos repetitivo.
`searchableKeys` define um array de chaves as quais a gente vai usar pra encontrar resultados.
`profileMatchFilter` vai ser true caso alguma das `searchableKeys` bata com o valor do filtro.

2024-10-13 11:58 UTC, goislimat commented on web/src/app/profiles-list/page.tsx
> +            {profiles
Uma pergunta, como fica a tela se o filtro não trouxer nenhum resultado?

2024-10-13 12:02 UTC, goislimat commented on web/src/app/profiles-list/page.tsx
> +"use client";
Temos que atualizar esse component pra remover o `useState` daqui e ele poder voltar a ser um server component. Caso contrário vai ficar ruim de fazer o fetch dos dados do backend aqui.

Talvez valha a pena a gente colocar um form em volta do input que faça a submissão dos dados. Isso vai mudar a URL e a gente pode pegar o parâmetro da URL pra filtrar. Vai ficar melhor até de compartilhar a URL já que o resultado da busca vai estar na URL.

Se vc não entender, me avisa que eu tento mandar um vídeo ou algo do tipo pra te instruir como fazer essa mudança.

2024-10-13 12:03 UTC, goislimat requested changes
Preciso que essas mudanças sejam feitas antes de aprovar.

2024-10-14 15:20 UTC, RafaRafa26 commented on web/src/app/profiles-list/page.tsx
> +            {profiles
Não aparece nada, está pensando em adicionar uma mensagem para o usuário?

![Captura de tela 2024-10-14 121536](https://github.com/user-attachments/assets/435265b2-6646-430f-a22e-2c3961b987c3)

2024-10-14 16:04 UTC, RafaRafa26 commented on web/src/app/profiles-list/page.tsx
> +                    }
Feito

2024-10-14 16:06 UTC, RafaRafa26 commented on web/src/app/profiles-list/page.tsx
> +"use client";
Não entendi muito bem como fazer

2024-10-14 20:38 UTC, goislimat commented on web/src/app/profiles-list/page.tsx
> +            {profiles
Seria bom ter algum feedback de que a busca não trouxe resultados

2024-10-14 20:44 UTC, goislimat commented on web/src/app/profiles-list/page.tsx
> +"use client";
Todos os tutoriais que eu encontrei não foram bons. Todos tem muito ruído. Coisas que são específicas do problema que eles estão resolvendo. Pra não te dar a resposta diretamente e te fazer trabalhar na solução do seu problema, eu vou criar um exemplo simplificado e te passo.

Pode ser que eu não consiga fazer hoje. Então eu te aconselho a pegar outro ticket enquanto eu vou fazendo esse vídeo, caso eu não consiga postar ele aqui pra vc rápido o suficiente.

2024-10-17 03:08 UTC, GiAmaral commented on web/src/app/profiles-list/page.tsx
> +                })
Não entendi como o `searchableKeys` ajuda nas buscas, pois os arrays contém as chaves, mas buscamos pelo valor e não as chaves, alguém poderia me explicar?

2024-10-17 16:44 UTC, RafaRafa26 commented on web/src/app/components/profile-card.tsx
> +        const reversedNames = names.toReversed();
Essa é uma função local, ou seja, ela está sendo definida dentro da função ProfileCard. O que ela faz é pegar as primeiras letras do nome e sobrenome do usuário para exibir no avatar de cada card de perfil.

2024-10-17 16:45 UTC, RafaRafa26 commented on web/src/app/profiles-list/page.tsx
> +const profiles = [
Esse array foi criado apenas para testar, futuramente será implementada a busca via API.

2024-10-17 16:46 UTC, RafaRafa26 commented on web/src/app/profiles-list/page.tsx
> +    const [search, setSearch] = useState("");
Essa foi a forma que o Thiago tinha me orientada a fazer, mas ele pediu pra mudar, vou subir um commit com as alterações.

2024-10-17 18:54 UTC, goislimat commented on web/src/app/profiles-list/page.tsx
> +            {profiles
Pra isso aqui funcionar, vc vai ter que desmembrar o filtro do map. Antes do return do HTML do componente vc vai fazer algo do tipo:

```javascript
const filteredResults = profiles
    .filter((profile) => {
        if (!q) {
            return true;
        }
        const formattedFilter = q.toLowerCase();
        const searchableKeys = [
            "name",
            "email",
            "level",
            "occupation",
        ] as Array<keyof typeof profile>;
        const profileMatchFilter = searchableKeys.find((key) => {
            const value = profile[key];
            return (
                typeof value === "string" &&
                value.toLowerCase().includes(formattedFilter)
            );
        });
        return profileMatchFilter;
    })
```

Depis no lugar de fazer um map pra poder renderizar os resultados, vc vai mandar uma checagem pra poder ver se tá vazio ou não e decidir se vai mostrar a seção com a mensagem de dados vazios ou os resultados filtrados.

```javascript
{filteredResults.length === 0 ? (
    <p>Mensagem que vc vai colocar pra indicar que a lista tá vazia</p>
) : (
    .map((profile) => {
        return <ProfileCard key={profile.id} profile={profile} />;
    })}
)}
```

2024-10-17 18:57 UTC, goislimat commented on web/src/app/components/profile-card.tsx
> +        const reversedNames = names.toReversed();
Se for sobre a função `toReversed` que vc tá falando, o que ela faz é inverter um array. Simples assim.

```javascript
const a = [1, 2, 3];

console.log(a.toReversed()); // [3, 2, 1]
```

2024-10-17 19:02 UTC, goislimat commented on web/src/app/profiles-list/page.tsx
> +                })
O `searchableKeys` diz pra gente quais os dados de cada usuários que vão ser usados pra fazer a busca. Nesse caso, não importa quais campos o objeto tenha, apenas `name`, `email`, `level` e `occupation` serão usados na busca.

Exemplo: se o usuário digitar `maria` esse valor será usado pra buscar nos campos listados acima se em algum lugar deles é cabe a substring `maria`.

Depois diz se deu pra enterder.

2024-10-17 19:37 UTC, GiAmaral commented on web/src/app/components/profile-card.tsx
> +        const reversedNames = names.toReversed();
Sim, é a função toReversed que estou querendo saber. Pelo que eu entendi vai pegar o nome do usuário, inverter a ordem (colocar o sobrenome primeiro), e no código abaixo pega a inicial que está na posição 0, é isso?

2024-10-17 19:38 UTC, GiAmaral commented on web/src/app/profiles-list/page.tsx
> +const profiles = [
Faz sentido, não tem fetch nesse código ainda

2024-10-17 20:16 UTC, GiAmaral commented on web/src/app/profiles-list/page.tsx
> +                })
Quando o usuário for fazer a pesquisa, o termo da busca só irá passar pelos campos dentro do searchabledKeys. Exemplo: quando o usuário digita "gerente", esse termo vai passar pelos campos "name", "level", até chegar em "ocupação" e ver que o termo bate e retornar a pesquisa, é isso?

2024-10-18 16:51 UTC, RafaRafa26 commented on web/src/app/profiles-list/page.tsx
> +            {profiles
![Captura de tela 2024-10-18 135050](https://github.com/user-attachments/assets/f35c9d54-723d-4040-832e-6be701ffd52b)

Só mudei um pouco o texto, acha que ficou bom ou precisa mudar?

2024-10-18 18:23 UTC, GiAmaral commented on web/src/app/profiles-list/page.tsx
> +        q: string | undefined;
O nome dessa variável não me parece semântico, não fica orgânico a leitura do código. Não afeta na execução, minha sugestão é renomeá-la para facilitar leituras futuras.

2024-10-18 18:23 UTC, GiAmaral commented on web/src/app/profiles-list/page.tsx
> +            return true;
Não entendi muito bem pq esse `return` é de valor `true`. Na minha leitura do código eu colocaria um `false` ou uma mensagem de erro ou um `null`... Algém poderia me explicar pq `true`?

2024-10-18 18:23 UTC, GiAmaral commented on web/src/app/profiles-list/page.tsx
> +        const formattedFilter = q.toLowerCase();
Acredito que seria melhor declarar essa variável fora do `if`.

2024-10-18 18:23 UTC, GiAmaral commented on web/src/app/profiles-list/page.tsx
> +        const searchableKeys = [
Mesma coisa aqui. Declarar fora do `if` pra evitar "ruídos". Achei confuso quando fui fazer a leitura do código.

2024-10-18 18:23 UTC, GiAmaral commented on web/src/app/profiles-list/page.tsx
> +        return searchableKeys.some((key) => {
Não entendi o que essa função callback `some` faz, alguém poderia me explicar?

2024-10-18 18:23 UTC, GiAmaral commented on web/src/app/profiles-list/page.tsx
> +        return searchableKeys.some((key) => {
A prop `key` dentro da função `some`, significa que é um elemento do array `searchableKey`?

2024-10-18 18:23 UTC, GiAmaral commented on web/src/app/profiles-list/page.tsx
> +            return (
Não entendi muito bem esse return.

2024-10-18 18:23 UTC, GiAmaral commented on web/src/app/profiles-list/page.tsx
> +                value.toLowerCase().includes(formattedFilter)
O que a função `includes` faz?

2024-10-18 18:23 UTC, GiAmaral commented on web/src/app/profiles-list/page.tsx
> +        return searchableKeys.some((key) => {
Não entendi esse return rsrsrsrsrs

2024-10-18 19:33 UTC, goislimat commented on web/src/app/profiles-list/page.tsx
> +        q: string | undefined;
`q` costuma é um padrão pra quando vc está fazendo uma busca simples com um único campo. Faz uma busca no google e vc vai ver que esse parâmetro `q` aparece na url.

https://www.google.com/search?q=o+que+%C3%A9+chinelo&sourceid=chrome&ie=UTF-8

`q=o+que+%C3%A9+chinelo&sourceid=chrome&ie=UTF-8`

2024-10-18 19:35 UTC, goislimat commented on web/src/app/profiles-list/page.tsx
> +            return true;
O `filter` mantém no array os valores que retornam `true` e remove quaisquer valores entendidos como `false`.

Nesse caso, se o parâmetro da busca estiver vazio ou `undefined` ou qualquer coisa que o js entenda como falso, ele vai retornar `true`. Isso acontece pq caso a busca esteja vazia, a gente quer que todos os resultados sejam retornados.

2024-10-18 19:35 UTC, goislimat commented on web/src/app/profiles-list/page.tsx
> +        const formattedFilter = q.toLowerCase();
Está fora do `if` só que depois.

2024-10-18 19:36 UTC, goislimat commented on web/src/app/profiles-list/page.tsx
> +        return searchableKeys.some((key) => {
Tô sentindo que há muitas dúvidas aqui. Vou fazer um vídeo.

2024-10-18 19:36 UTC, goislimat commented on web/src/app/profiles-list/page.tsx
> +                value.toLowerCase().includes(formattedFilter)
Vai estar no vídeo

2024-10-21 17:51 UTC, goislimat approved these changes

2024-10-21 20:16 UTC, JaqAmaral approved these changes

2024-10-22 18:30 UTC, merged