Connecting front-end and back-end of reset-password screen
Somehow-I-Code/marquei pull request #136
Opened 2024-11-04 02:50 UTC by RafaRafa26

# [Título do seu pull request]

## Qual problema esse pull request resolve?

## Como o seu código resolve esse problema?

## Quais os passos para testar essa feature/bug?

2024-11-04 15:07 UTC, goislimat commented on web/src/app/reset-password/[token]/page.tsx
> +        revalidatePath("/login");
Não precisa revalidar nenhum path. Basta redirecionar pra tela de login.

2024-11-04 15:07 UTC, goislimat commented on web/src/app/reset-password/[token]/page.tsx
> +                "content-type": "application/json",
o token vai aqui no header. Dá uma olhada no `new-company` do front end ou qualquer outro `new-(alguma coisa)` que esteja funcionando.

2024-11-04 15:10 UTC, goislimat commented on web/src/app/reset-password/[token]/page.tsx
> +                "content-type": "application/json",
Corrigindo aqui. Esse token tá certo sendo passado no body. Essa rota não deve estar autenticada mesmo.

2024-11-05 19:49 UTC, goislimat commented on api/src/http/routes/create-new-password.ts
> +        const profile = await profileRepository.findById(decoded.id, true);
```suggestion
        const profile = await profileRepository.findById(decoded.id);
```

2024-11-05 19:50 UTC, goislimat commented on api/src/http/routes/create-new-password.ts
> +        await profileRepository.updatePassword(profile.id, hashedPassword);
```suggestion
        await profileRepository.updatePassword(profile.id, newPassword);
```

2024-11-07 16:21 UTC, goislimat commented on api/src/validators/create-new-password.ts
> +});
Adiciona o `token` nesse schema aqui.

2024-11-07 16:22 UTC, goislimat commented on api/src/http/routes/create-new-password.ts
> +        };
Usa o `.parse` no `request.body` aqui depois que vc adicionar o token ao validator. Pq aí vc já checa tudo de uma única vez.

2024-11-07 16:25 UTC, goislimat commented on api/src/http/routes/create-new-password.ts
> +        try {
Esse `try/catch` aqui não faz sentido pq vc não tá dando `throw` em lugar nenhum e nada aqui pode lançar um erro.

2024-11-07 16:26 UTC, goislimat commented on api/src/http/routes/create-new-password.ts
> +        }
Esse parse vai passar a ser feito lá em cima quando vc adicionar o token ao body da requisição.

2024-11-07 16:27 UTC, goislimat commented on api/src/http/routes/create-new-password.ts
> +    });
```suggestion
        if (newPassword !== repeatPassword) {
            return reply.status(httpCodes.BAD_REQUEST).send({
                message:
                    "A confirmação de senha não coincide com a nova senha.",
            });
        }
        
        const profile = await profileRepository.findById(decoded.id);

        if (!profile) {
            return reply
                .status(httpCodes.NOT_FOUND)
                .send({ message: "Usuário não encontrado!" });
        }

        const { newPassword, repeatPassword } = createNewPassword;

        await profileRepository.updatePassword(profile.id, newPassword);

        return reply
            .status(httpCodes.SUCCESS)
            .send({ message: "Senha atualizada com sucesso!" });
    });
```

Trocando aqui as ordem das coisa pq não faz sentido buscar por um perfil se o usuário enviou senhas que não batem.

2024-11-07 16:33 UTC, goislimat requested changes
Faltou um arquivo http com a request pra poder alterar a senha.

Talvez mudar o arquivo lá do reset de senha pra ser algo assim funcione.

```http
# @name reset_password
POST {{host}}/reset-password
content-Type: application/json

{
    "email": "sudo@marquei.com"
}

###
@token = {{reset_password.response.body.$.token}}

PATCH {{host}}/create-new-password
content-Type: application/json

{
    "password": "1234567890",
    "repeatPassword": "1234567890",
    "token": {{token}}
}
```

Se exatamente assim não funcionar, tenta encontrar o problema ou manda mensagem pra gente dar uma olhada.

2024-11-08 10:42 UTC, goislimat commented on api/requests/reset-password/reset-password.http
> +}
```suggestion
{
    "newpassword": "1234567890",
    "repeatPassword": "1234567890",
    "token": "{{token}}"
}

```

2024-11-08 10:51 UTC, goislimat commented on api/src/validators/create-new-password.ts
> +    token: z.string().min(1, { message: "O token é obrigatório." }),
```suggestion
    token: z.string({
        required_error: "O token é obrigatório.",
        invalid_type_error: "Formato do token inválido.",
    })
```

2024-11-08 14:28 UTC, RafaRafa26 commented on api/requests/reset-password/reset-password.http
> +}
![image](https://github.com/user-attachments/assets/77235a2a-283a-4fe4-9c99-fa88215df568)

2024-11-08 20:54 UTC, goislimat approved these changes

2024-11-09 14:57 UTC, merged