Solved error on new category screen
Somehow-I-Code/marquei pull request #141
Opened 2024-11-18 20:28 UTC by JaqAmaral

# PROBLEMA RESOLVIDO: ERRO NA TELA DE NOVA CATEGORIA

## Qual problema esse pull request resolve?
Ao fazer teste da tela apresentou erro de companyId que é obrigatório. Para resolver o problema, foram adicionados o companyId nos arquivos. Também foi incluída a lógica para decodificar o session e obter o companyId do usuário logado para fazer a criação de nova categoria.

## Como o seu código resolve esse problema?
Os passos para a resolução do problema foram:
- Foi identificado um erro relacionado ao companyId, então ele foi adicionado ao arquivo `new-category-form.tsx` no **FormSchema**, na **Props** e no **FormField**. Da mesma forma, foi incluído na pasta **types**.
- No campo FormField do **companyId**, foi definido a tag Input do type="hidden", para que o usuário não veja na tela, mas ainda será enviado nos dados.
- Antes de enviar para o banco de dados, o **companyId** passa por uma conversão de **string** para o **number**.
- Foi adicionado o jwt.decode para decodificar a sessão e obter o companyId do usuário logado, permitindo a criação da nova categoria.

## Quais os passos para testar essa feature/bug?
- No terminal, foi instalado o pacote lucide-react: 
	- Digite os comandos: `cd web && npm i && make web && npm i.`
	- Em seguida: `make run`
- Abra o navegador e acesse [localhost:3001/new-category](url) para testar a criação de uma nova categoria. 
	
Prints de cada nível de usuário:
SUDO/ADMIN/USER - Prisma studio

![Captura de tela 2024-11-14 115940](https://github.com/user-attachments/assets/ae7ac936-b8cd-48de-a73a-5f0ff14ce20a)

2024-11-19 12:18 UTC, goislimat commented on web/src/app/new-category/page.tsx
> +            companyId: Number(data.companyId),
Vc pode usar esse `companyId` que vc tirou do token mesmo. Não tem necessidade de passar ele pro `NewCategoryForm` já que o campo está oculto lá no componente. Isso aumenta a complexidade do form (mais uma coisa pra olhar) e não entrega valor.

Eu tiraria qualquer menção ao `companyId` do form e seguiria só com essa alteração.

Antes de commitar, tenha certeza de que tá tudo funcionando.

2024-11-19 12:18 UTC, goislimat requested changes
Eu gostaria de ver a alteração que eu sugeri implementada.

2024-11-19 14:39 UTC, JaqAmaral commented
Fiz alterações que pediu, adicionei o companyId (token) na variável body. E criei uma nova categoria para teste (Imagem abaixo):

![image](https://github.com/user-attachments/assets/3650fd71-520c-4eea-9e6b-2ec2316182a5)

2024-11-19 14:42 UTC, JaqAmaral commented
> Eu gostaria de ver a alteração que eu sugeri implementada.

As alterações foram feitas, adicionei o companyId (token) na variável body e tirei todos companyId no form. E criei uma nova categoria para teste, como mostra na imagem abaixo:

![image](https://github.com/user-attachments/assets/7dc4c534-922e-441a-983a-be3a652c6985)

2024-11-21 12:09 UTC, goislimat approved these changes

2024-11-21 17:39 UTC, merged