Adicionando ação de eye/eyeOff
Somehow-I-Code/marquei pull request #86
Opened 2024-05-13 18:30 UTC by JaqAmaral

Parte ao entrar na página de "Alterar a senha":
![image](https://github.com/Somehow-I-Code/marquei/assets/133810168/de2c228f-8a22-48fb-8d92-0bf974cc4384)

Esta tela abaixo ao clicar o botão eye, muda para eyeOff.
![image](https://github.com/Somehow-I-Code/marquei/assets/133810168/7abf9801-f50f-4e08-a2d8-f63efdc6e630)

2024-05-13 18:34 UTC, JaqAmaral commented
Criando um id de cada input e usando o id criado para mostrar cada ação do tag button.

2024-05-13 18:38 UTC, JaqAmaral commented on web/src/app/change-password/components/change-password-form.tsx
> +                                        id="oldPassword"
Criando id para cada atributo, assim usa este id na tag button para mudar o icon

2024-05-13 23:08 UTC, GiAmaral requested changes

2024-05-13 23:08 UTC, GiAmaral commented on web/src/app/change-password/components/change-password-form.tsx
>          console.log(data);
Acho que o console.log não pode estar na PR, ou seja, tem que tirar.

2024-05-13 23:10 UTC, GiAmaral commented on web/src/app/change-password/components/change-password-form.tsx
>          console.log(data);
Acho que o console.log não pode estar na PR, ou seja, tem que tirar.

2024-05-14 14:54 UTC, RafaRafa26 approved these changes

2024-05-14 14:54 UTC, RafaRafa26 approved these changes

2024-05-14 19:03 UTC, goislimat commented on web/src/app/change-password/components/change-password-form.tsx
> +    };
Vc sabe me explicar como que, por exemplo, ele sabe que tem que mostrar a senha do campo `newPassword`.

2024-05-14 23:25 UTC, GiAmaral approved these changes

2024-05-17 12:40 UTC, goislimat commented on web/src/app/change-password/components/change-password-form.tsx
> +    };
hsthsthsth

2024-05-17 13:38 UTC, goislimat approved these changes

2024-05-17 17:54 UTC, merged