Fazer a submissão dos dados do form do front para login
Somehow-I-Code/marquei pull request #87
Opened 2024-05-14 14:06 UTC by RafaRafa26

2024-05-14 18:09 UTC, JaqAmaral approved these changes

2024-05-14 23:40 UTC, GiAmaral requested changes

2024-05-14 23:40 UTC, GiAmaral commented on web/src/app/login/components/login-form.tsx
> +        console.log(token);
Vamos tentar não subir o console.log para não ir pra main.

2024-05-14 23:40 UTC, GiAmaral commented on web/src/app/login/page.tsx
> +        console.log(credentials);
Mesma coisa, vamos tentar não subir console.log.

2024-05-14 23:41 UTC, GiAmaral commented on web/src/app/login/page.tsx
> +        console.log(credentials);
Mesma coisa, vamos tentar não subir console.log.

2024-05-14 23:42 UTC, goislimat approved these changes
Concordo com os pontos da Gisele. Mas já vou deixar aprovado.

2024-05-15 12:06 UTC, GiAmaral approved these changes

2024-05-15 16:42 UTC, merged