Create reset password endpoint
Somehow-I-Code/marquei pull request #99
Opened 2024-06-06 15:27 UTC by RafaRafa26

# [Implementação do Endpoint de Reset de Senha]

## Qual problema esse pull request resolve?
Este pull request implementa um endpoint para resetar a senha dos usuários. 

## Como o seu código resolve esse problema?
O código implementa o endpoint `/reset-password` que aceita requisições POST. Quando um usuário faz uma solicitação para resetar a senha, o endpoint valida o email fornecido e verifica se ele existe no banco de dados. Se o email não for encontrado, uma resposta 404 é retornada com a mensagem "Email não encontrado".

## Quais os passos para testar essa feature/bug?

1. Iniciar o servidor: Rodar a aplicação com  `make run`
2. Configurar o Hoppscotch/Postman:

- Método: POST
- URL: http://localhost:8080/reset-password
- Cabeçalho: Content-Type: application/json
- Corpo da requisição:
{
    "email": "email@exemplo.com"
}
4. Enviar a requisição: Clique em Mandar ou Send.
5. Verificar a resposta:

- Se o email existir no banco de dados, a resposta deve ser 200 OK 
![Captura de tela 2024-06-06 115836](https://github.com/Somehow-I-Code/marquei/assets/129136093/e23658c7-2b0b-4594-9b78-e312c0a6cf85)

- Se o email não existir no banco de dados, a resposta deve ser 404 Not Found com a mensagem { "error": "Email não encontrado" }.
![Captura de tela 2024-06-06 115920](https://github.com/Somehow-I-Code/marquei/assets/129136093/c08359b5-ec24-4413-bcdb-8010f29233fa)

2024-06-07 00:04 UTC, GiAmaral approved these changes

2024-06-07 12:16 UTC, goislimat commented on api/src/http/routes/reset-password.ts
> +
Eu acabei aprovando, mas vc poderia adicionar um arquivo `.http` pra esse endpoint pra já deixar salvo como vai ser a request pra esse endpoint. Os PRs que criam endpoints são os melhores candidatos pra adicionar novos arquivos de requests.

Qualquer coisa, dá uma olhada nesse PR.

https://github.com/Somehow-I-Code/marquei/pull/94

2024-06-07 12:18 UTC, JaqAmaral approved these changes

2024-06-07 12:25 UTC, goislimat requested changes
Mudei meu review só pra garantir que as mudanças serão feitas antes do merge.

2024-06-08 15:06 UTC, RafaRafa26 commented on api/src/http/routes/reset-password.ts
> +
Status 200 

![Captura de tela 2024-06-08 120205](https://github.com/Somehow-I-Code/marquei/assets/129136093/d998e1f6-d12d-439d-ba76-fcd7d5f769a2)

Status 404 

![Captura de tela 2024-06-08 120247](https://github.com/Somehow-I-Code/marquei/assets/129136093/38bee5ed-3bbe-476b-9416-82c527dc7a2c)

2024-06-08 16:01 UTC, goislimat approved these changes

2024-06-08 19:19 UTC, merged